plugins {
    id 'java'
}

group = 'studio.whiteflame'
version = '0.0.1'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'uk.co.caprica:vlcj:4.10.1'
    implementation 'uk.co.caprica:vlcj-natives:4.7.0'
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}